spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: { spring.application.name }
#  gateway:
#    discovery:
#      locator:
#        enabled: true
#    gateway:
#      httpclient:
#        ssl:
#          useInsecureTrustManager: true
#  security:
#    ssl:
#      enabled: false

server:
  port: 8080

jwt:
  public-key: classpath:key/public.pem

logging:
  level:
    org.springframework.security: DEBUG