spring:
  application:
    name: auth
  cloud:
    consul:
      host: localhost
      port: 9000
      discovery:
        service-name: { spring.application.name }
  datasource:
    url: jdbc:h2:mem:authdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  key:
    public: classpath:key/public.pem
    private: classpath:key/private.pem
  expiration: 3600 # seconds

server:
  port: 9000

logging:
  level:
    org.springframework.security: DEBUG