server:
    port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: http://localhost:1980/root/config-repo.git
          default-label: main
          search-paths: '{application}'  # ?? ??
